import 'package:frameguard/src/reporting/comparison.dart';
import 'package:frameguard/src/reporting/report.dart';

/// Builds Markdown suitable for PR comments and CI summaries.
///
/// Local-only — no network calls. Designed for GitHub / GitLab job summaries.
class MarkdownReportBuilder {
  /// Creates a builder for [report].
  MarkdownReportBuilder(this.report, {this.comparison});

  /// Source report.
  final FrameGuardReport report;

  /// Optional baseline comparison.
  final ComparisonResult? comparison;

  /// Full Markdown document.
  String build() {
    final r = report;
    final status = _statusEmoji;
    final buf = StringBuffer()
      ..writeln('## FrameGuard — `${r.scenario}`')
      ..writeln()
      ..writeln(
        '| | |',
      )
      ..writeln('|---|---|')
      ..writeln('| **Result** | $status $_resultLabel |')
      ..writeln('| **Frames** | ${r.stats.totalFrames} |')
      ..writeln('| **Jank rate** | ${_pct(r.stats.jankRate)} |')
      ..writeln('| **p50 / p95 / p99** | '
          '${_ms(r.stats.p50)} / ${_ms(r.stats.p95)} / ${_ms(r.stats.p99)} |')
      ..writeln('| **Refresh** | ${r.refreshRateHz.toStringAsFixed(0)} Hz |')
      ..writeln('| **Mode** | ${r.device.buildMode.name} |')
      ..writeln('| **Device** | ${_esc(r.device.summary())} |')
      ..writeln();

    if (r.debugModeWarning != null) {
      buf
        ..writeln('> **Warning:** ${_esc(r.debugModeWarning!)}')
        ..writeln();
    }

    if (r.budgetEvaluation != null) {
      buf
        ..writeln('### Budget')
        ..writeln()
        ..writeln('| Check | Result | Actual | Limit |')
        ..writeln('|---|---|---|---|');
      for (final c in r.budgetEvaluation!.checks) {
        buf.writeln(
          '| ${_esc(c.name)} | ${c.passed ? 'PASS' : 'FAIL'} | '
          '${_esc(c.actual)} | ${_esc(c.limit)} |',
        );
      }
      buf.writeln();
    }

    if (comparison != null) {
      buf
        ..writeln('### Baseline comparison')
        ..writeln()
        ..writeln(
          comparison!.isRegression
              ? '**Regression detected.**'
              : 'No regression.',
        )
        ..writeln()
        ..writeln('| Metric | Baseline | Current | Δ |')
        ..writeln('|---|---|---|---|');
      for (final d in comparison!.deltas) {
        final deltaPct = '${(d.relativeChange * 100).toStringAsFixed(1)}%';
        final mark = d.regressed ? ' ⚠️' : '';
        buf.writeln(
          '| ${_esc(d.name)}$mark | ${d.baselineLabel} | '
          '${d.currentLabel} | $deltaPct |',
        );
      }
      buf.writeln();
    }

    final diagnostics = r.explanation?.diagnostics ?? const [];
    if (diagnostics.isNotEmpty) {
      buf
        ..writeln('### Findings')
        ..writeln();
      for (final d in diagnostics) {
        buf.writeln('- **${d.id}** — `${d.code}`');
      }
      buf.writeln();
    }

    if (r.explanation?.primaryFinding != null &&
        r.explanation!.primaryFinding.isNotEmpty) {
      buf
        ..writeln('**Primary:** ${_esc(r.explanation!.primaryFinding)}')
        ..writeln();
    }

    final tips = r.explanation?.recommendations
            .expand((rec) => rec.suggestions)
            .toList() ??
        const [];
    if (tips.isNotEmpty) {
      buf
        ..writeln('### Recommendations')
        ..writeln();
      for (final t in tips.take(5)) {
        buf.writeln('- ${_esc(t)}');
      }
      buf.writeln();
    }

    buf.writeln(
      '<sub>Generated by FrameGuard ${r.frameguardVersion} · '
      'local report · no telemetry</sub>',
    );
    return buf.toString();
  }

  /// Compact single-line summary for CI logs.
  String oneLiner() {
    final r = report;
    return 'FrameGuard[${r.scenario}] $_resultLabel '
        'frames=${r.stats.totalFrames} jank=${_pct(r.stats.jankRate)} '
        'p95=${_ms(r.stats.p95)} p99=${_ms(r.stats.p99)}';
  }

  String get _resultLabel {
    if (comparison?.isRegression ?? false) return 'REGRESSION';
    if (report.budgetEvaluation != null) {
      return report.passed ? 'PASS' : 'FAIL';
    }
    return 'OK';
  }

  String get _statusEmoji {
    if (comparison?.isRegression ?? false) return '❌';
    if (report.budgetEvaluation != null) {
      return report.passed ? '✅' : '❌';
    }
    return 'ℹ️';
  }

  static String _ms(Duration d) =>
      '${(d.inMicroseconds / 1000).toStringAsFixed(1)} ms';

  static String _pct(double v) => '${(v * 100).toStringAsFixed(1)}%';

  static String _esc(String s) =>
      s.replaceAll('|', '\\|').replaceAll('\n', ' ');
}
